# Travis-CI Build for libadt
# see travis-ci.org for details

language: cpp

sudo: required

branches:
  only:
    - main

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential cmake check valgrind lcov

before_script:
  - mkdir build

script:
  - cd build
  - cmake ..
  - make
  - cd tests
  - ./runUnitTests
  - make gcov

after_success:
  - bash <(curl -s https://codecov.io/bash)
