name: Awesome CI Workflow
on: [push, pull_request]
permissions:
  contents: write

jobs:
  MainSequence:
    name: Code Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
      - name: requirements
        run: | 
          sudo apt-get -qq update
          sudo apt-get -qq install clang-tidy clang-format
      - name: Setup Git Specs
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          - name: Upload coverage reports to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: CSRT-NTUA/AlgoPlus

